import = ["~/.config/alacritty/catppuccin-mocha.toml"]

shell = "zsh"

[env]
TERM = "xterm-256color"

[window]
decorations = "none"

[window.dimensions]
columns = 100
lines = 24

[window.padding]
x = 3
y = 3

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
